model:
  sequence_len: 72
  l_sequence_hid: 64
  g_sequence_hid: 128
  input_dim: 10
  emb_dim: 16
  split: 6
  modes: 3
  dropout: 0.

md:
  alpha: 2000
  tau: 0
  K: 2
  DC: 0
  init: 1
  tol: 1e-7
  max_N: 50
  device: 'cuda:0'

train:
  batchsize: 4
  device: 'cuda:0'
  epochs: 1600
  lr: 0.001
  itr_per_epoch: 100000
